export const FETCH_NEWS = 'FETCH_NEWS'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE'

export const GENERAL_NEWS_REQUEST = 'GENERAL_NEWS_REQUEST'
export const GENERAL_NEWS_SUCCESS = 'GENERAL_NEWS_SUCCESS'
export const GENERAL_NEWS_FAILURE = 'GENERAL_NEWS_FAILURE'